=== 01Hub/ALFS/archive/DTD/trunk/ALFS.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
       ALFS :    Document Type Definition
       Version : SVN
       Author:   V. Dzuba
       Updates:  Kevin P. Fleming
       Date:     July 3, 2004

       The current version of the DTD is available at:
             http://www.linuxfromscratch.org/alfs/downloads/stable

       The current version of its documentation is available at:
             http://www.linuxfromscratch.org/alfs/view/dtd

       This DTD is published under both BSD and GNU licenses.
-->

<!ENTITY lt     "&#38;#60;"> 
<!ENTITY gt     "&#62;"> 
<!ENTITY amp    "&#38;#38;"> 
<!ENTITY apos   "&#39;"> 
<!ENTITY quot   "&#34;"> 

<!ENTITY % ops "configure | copy | download | execute | if | link | make | mkdir | move | ownership | patch | permissions | remove | search_replace | stage | textdump | unpack">
<!ENTITY % tests "test | package-built | package-version | and | or | not">

<!ELEMENT alfs           ((%ops; | include | package | packagegroup)+)>
<!ATTLIST alfs
          base           CDATA #IMPLIED
          version        CDATA #FIXED "3.2"
	  xml:base	 CDATA #IMPLIED
	  xmlns:xi	 CDATA #IMPLIED>

<!ELEMENT and            ((%tests;)+)>

<!ELEMENT archive        (#PCDATA)>

<!ELEMENT base           (#PCDATA)>

<!ELEMENT configure      ((param | prefix)*)>
<!ATTLIST configure
          base           CDATA #IMPLIED
          command        CDATA #IMPLIED>

<!ELEMENT content        (#PCDATA)>

<!ELEMENT copy           (option*, source+, destination)>
<!ATTLIST copy
          base           CDATA #IMPLIED>

<!ELEMENT description    (para | list)*>

<!ELEMENT destination    (#PCDATA)>

<!ELEMENT digest         (#PCDATA)>
<!ATTLIST digest         
          type           CDATA     "md5">

<!ELEMENT download       (file, url*, digest?)>
<!ATTLIST download
          base           CDATA #IMPLIED>

<!ELEMENT else           (stageinfo?, (%ops;)*)>

<!ELEMENT execute        (((param | prefix)*) | content)>
<!ATTLIST execute
          base           CDATA #IMPLIED
          command        CDATA #IMPLIED>

<!ELEMENT environment    (variable+)>

<!ELEMENT file           (#PCDATA)>

<!ELEMENT find           (#PCDATA)>

<!ELEMENT if		 ((%tests;)+, then?, else?)>

<!ELEMENT item           (#PCDATA)>

<!ELEMENT include        EMPTY>
<!ATTLIST include
          href           CDATA #REQUIRED>

<!ELEMENT link           (option*, target+, name)>
<!ATTLIST link
          base           CDATA #IMPLIED
	  type           (hard | symbolic) "symbolic">

<!ELEMENT list           (item | list)+>
<!ATTLIST list
          type           (bullet | number) "bullet">

<!ELEMENT make           ((param | prefix)*)>
<!ATTLIST make
          base           CDATA #IMPLIED>

<!ELEMENT mkdir          (option?, permissions?, name+)>
<!ATTLIST mkdir
          base           CDATA #IMPLIED>
          
<!ELEMENT move           (option?, source+, destination)>
<!ATTLIST move
          base           CDATA #IMPLIED>

<!ELEMENT name           (#PCDATA)>

<!ELEMENT not            (%tests;)>

<!ELEMENT option         (#PCDATA)>

<!ELEMENT or             ((%tests;)+)>

<!ELEMENT ownership      (option?, name+)>
<!ATTLIST ownership
          base           CDATA #IMPLIED
          user           CDATA #IMPLIED
	  group          CDATA #IMPLIED>
          
<!ELEMENT package        (packageinfo?, stage+)>
<!ATTLIST package
          name           CDATA #REQUIRED
          version        CDATA #REQUIRED>

<!ELEMENT packageinfo    (description?, requires*, utilizes*)>

<!ELEMENT packagegroup   (package+)>

<!ELEMENT para           (#PCDATA)>

<!ELEMENT param          (#PCDATA)>

<!ELEMENT patch          (digest?, reference*, file, (param | prefix)*)>
<!ATTLIST patch
          base           CDATA #IMPLIED
          mode           (forward | reverse) "forward"
          path_strip     CDATA #IMPLIED>

<!ELEMENT permissions    (option?, name*)>
<!ATTLIST permissions
          base           CDATA #IMPLIED
          mode           CDATA #REQUIRED>

<!ELEMENT prefix         (#PCDATA)>

<!ELEMENT reference      (#PCDATA)>

<!ELEMENT remove         (file+)>
<!ATTLIST remove
          base           CDATA #IMPLIED>

<!ELEMENT replace        (#PCDATA)>

<!ELEMENT requires       (name, version*)>

<!ELEMENT root           (#PCDATA)>

<!ELEMENT search_replace (file, find, replace)>
<!ATTLIST search_replace
          base           CDATA #IMPLIED
          mode           (append | replace | prepend) "replace"
          global         (yes | no) "yes">

<!ELEMENT shell          (#PCDATA)>

<!ELEMENT stage          (stageinfo?, (%ops; | package | packagegroup)+)>
<!ATTLIST stage
          name           CDATA #IMPLIED>
          
<!ELEMENT source         (#PCDATA)>

<!ELEMENT stageinfo      (root?, user?, environment?, base?, shell?)>

<!ELEMENT target         (#PCDATA)>

<!ELEMENT test           (#PCDATA)>

<!ELEMENT textdump       (file, content)>
<!ATTLIST textdump
          base           CDATA #IMPLIED
	  mode           (append | overwrite) "overwrite">

<!ELEMENT then           (stageinfo?, (%ops;)*)>

<!ELEMENT unpack         (digest?, reference*, archive)>
<!ATTLIST unpack
          base           CDATA #IMPLIED>

<!ELEMENT url            (#PCDATA)>

<!ELEMENT user           (#PCDATA)>

<!ELEMENT utilizes       (name, version*)>

<!ELEMENT variable       (#PCDATA)>
<!ATTLIST variable
          name           CDATA #REQUIRED
	  mode           (append | prepend) #IMPLIED>

<!ELEMENT version        (#PCDATA)>
<!ATTLIST version
          condition      (eq | ne | gt | ge | lt | le) #REQUIRED>

=== 01Hub/ALFS/archive/profiles/CLFS/trunk/prep/creatingcrosstoolsdir.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">

%general_entities;
]>

<alfs>
  <stage name="Creating $LFS/cross-tools">
    <stageinfo>
      <user>&lfs-user;</user>
    </stageinfo>
    <mkdir>
      <option>parents</option>
      <name>&lfs-user-dir;/cross-tools</name>
    </mkdir>
  </stage>
  <stage name="Creating /cross-tools">
    <link>
      <option>force</option>
      <target>&lfs-user-dir;/cross-tools</target>
      <name>/</name>
    </link>
  </stage>
<!--
  $LastChangedDate$
  $LastChangedBy$
  $LastChangedRevision$
-->
</alfs>

=== 01Hub/ALFS/archive/profiles/BLFS/branches/5.1/chapter30/nautilus.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/packages/ch30.ent">
<!ENTITY % config_entities SYSTEM  "../config/config.ent">

%general_entities;
%package_entities;
%config_entities;

]>
<alfs>
  <package name="nautilus" version="&nautilus-version;">
    <packageinfo>
      <requires>
        <name>eel</name>
      </requires>
      <requires>
        <name>librsvg</name>
      </requires>
      <requires>
        <name>gnome-desktop</name>
      </requires>
      <utilizes>
        <name>startup-notification</name>
      </utilizes>
      <utilizes>
        <name>esound</name>
      </utilizes>
      <utilizes>
        <name>libgsf</name>
      </utilizes>
      <utilizes>
        <name>cdparanoia</name>
      </utilizes>
      <utilizes>
        <name>libjpeg</name>
      </utilizes>
    </packageinfo>
    <stage name="Unpacking">
      <unpack>
        <archive>&packages_dir;/&nautilus-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Installing">
      <stageinfo>
        <base>&build_dir;/&nautilus-directory;</base>
      </stageinfo>
      <configure>
        <param>--prefix=`pkg-config --variable=prefix ORBit-2.0`</param>
        <param>--libexecdir=`pkg-config --variable=prefix ORBit-2.0`/sbin</param>
        <param>--sysconfdir=/etc/gnome</param>
      </configure>
      <make />
      <make>
        <param>install</param>
      </make>
    </stage>
    <stage name="Cleanup">
      <remove>&build_dir;/&nautilus-directory;</remove>
    </stage>
  </package>
</alfs>

=== 01Hub/ALFS/profiles/BLFS/branches/build-as-user/chapter18/ncpfs.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/packages/ch18.ent">
<!ENTITY % config_entities SYSTEM  "../config/config.ent">
<!ENTITY % files SYSTEM "../config/files.ent">

%general_entities;
%package_entities;
%config_entities;
%files;

<!ENTITY bootscripts-get SYSTEM "../config/bootscripts_get.ent">
<!ENTITY bootscripts-clean SYSTEM "../config/bootscripts_clean.ent">

]>
<alfs>
  <package name="ncpfs" version="&ncpfs-version;">
    <packageinfo>
      <utilizes>
        <name>linuxpam</name>
      </utilizes>
      <utilizes>
        <name>php</name>
      </utilizes>
    </packageinfo>
    <stage name="Unpacking">
      <stageinfo>
	<user>&build-user;</user>
      </stageinfo>
      <unpack>
        <digest>&ncpfs-md5;</digest>
	<archive>&packages_dir;/&ncpfs-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    &bootscripts-get;
    <stage name="Building">
      <stageinfo>
        <base>&build_dir;/&ncpfs-directory;</base>
      </stageinfo>
      <configure>
        <param>--prefix=""</param>
        <param>--includedir=/usr/include</param>
        <param>--mandir=/usr/share/man</param>
        <param>--datadir=/usr/share</param>
      </configure>
      <make />
    </stage>
    <stage name="Installing">
      <stageinfo>
	<base>&build_dir;/&ncpfs-directory;</base>
      </stageinfo>
      <make>
        <param>install</param>
      </make>
      <make>
        <param>install-dev</param>
      </make>
    </stage>
    <stage name="Installing bootscript and configuration">
      <stageinfo>
        <base>&build_dir;/&blfs-bootscripts-directory;</base>
      </stageinfo>
      <make>
        <param>install-service-ipx</param>
      </make>
    <copy>
      <source>&blfs-config;/etc/sysconfig/network-devices/ifconfig.eth0/ipx</source>
      <destination>/etc/sysconfig/network-devices/ifconfig.eth0/ipx</destination>
    </copy>
    </stage>
    &bootscripts-clean;
    <stage name="Cleanup">
      <remove>&build_dir;/&ncpfs-directory;</remove>
    </stage>
  </package>
</alfs>

=== 01Hub/ALFS/profiles/LFS/branches/testing/chapter09/nALFS.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd" [
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">

%general_entities;
%package_entities;
]>

<alfs>

<package name="nALFS" version="&nALFS-version;">
	<stage name="Unpacking.">
		<unpack>
			<digest>&nALFS-md5;</digest>
			<archive>&packages_dir;/&nALFS-package;</archive>
			<destination>&build_dir;</destination>
		</unpack>
	</stage>

	<stage name="Installing.">
		<stageinfo>
			<base>&build_dir;/&nALFS-directory;</base>
		</stageinfo>

		<configure>
			<param>--prefix=/usr</param>
		</configure>

		<make />

		<make>
			<param>install</param>
		</make>
	</stage>

	<stage name="Cleaning up.">
		<remove>&build_dir;/&nALFS-directory;</remove>
	</stage>
</package>

</alfs>

=== 01Hub/ALFS/profiles/LFS/trunk/chapter05/gcc-pass2.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">

%general_entities;
%package_entities;
]>
<alfs>
  <package name="gcc-pass2" version="&gcc-version;">
    <stage name="Download and Check">
      <download>
	<file>&gcc-package;</file>
	<url>&gcc-package-url;</url>
	<destination>&packages_dir;</destination>
	<digest>&gcc-md5;</digest>
      </download>
      <download>
	<file>&gcc-specs-patch;</file>
	<url>&gcc-patches-url;</url>
	<destination>&packages_dir;</destination>
	<digest>&gcc-specs-patch-md5;</digest>
      </download>
    </stage>
    <stage name="Unpacking">
      <unpack>
        <archive>&packages_dir;/&gcc-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
      <mkdir base="&build_dir;">
        <option>parents</option>
        <name>gcc-build</name>
      </mkdir>
    </stage>
      <!-- Run the following command:  expect -c "spawn ls"
If you receive the message:
        The system has no more ptys.  Ask your system administrator to create more.
Your host distribution is not set up for proper PTY operation. In this case there is no point in running the test
suites for GCC and Binutils until you are able to resolve the issue.
      -->
    <stage name="Patching">
      <stageinfo>
        <environment>
          <variable name="CFLAGS" />
          <variable name="CXXFLAGS" />
        </environment>
        <base>&build_dir;/&gcc-directory;</base>
      </stageinfo>
      <copy>
       <source>gcc/Makefile.in</source>
       <destination>gcc/Makefile.in.orig</destination>
      </copy>
      <execute command="sed">
        <param>'s@\./fixinc\.sh@-c true@'</param>
        <param>gcc/Makefile.in.orig &gt; gcc/Makefile.in</param>
      </execute>
      <copy>
	<source>gcc/Makefile.in</source>
	<destination>gcc/Makefile.in.tmp</destination>
      </copy>
      <execute command="sed">
        <param>'s/^XCFLAGS =$/&real-amp; -fomit-frame-pointer/'</param>
        <param>gcc/Makefile.in.tmp &gt; gcc/Makefile.in</param>
      </execute>
      <patch>
        <param>-N</param>
        <param>-p1</param>
        <param>-i &packages_dir;/&gcc-specs-patch;</param>
      </patch>
    </stage>
    <stage name="Installing">
      <stageinfo>
        <environment>
          <variable name="CFLAGS" />
          <variable name="CXXFLAGS" />
        </environment>
        <base>&build_dir;/gcc-build</base>
      </stageinfo>

      <configure command="../&gcc-directory;/configure">
        <param>--prefix=/tools</param>
        <param>--with-local-prefix=/tools</param>
        <param>--enable-clocale=gnu</param>
        <param>--enable-shared</param>
        <param>--enable-threads=posix</param>
        <param>--enable-__cxa_atexit</param>
        <param>--enable-languages=c,c++</param>
        <param>--disable-libstdcxx-pch</param>
      </configure>
      <make>
        <param>&jlevel;</param>
      </make>
      <!--
      <make>
        <param>-k check</param>
      </make>
      <execute command="../&gcc-directory;/contrib/test_summary" />
      -->
      <make>
        <param>install</param>
      </make>
    </stage>
    <stage name="Cleanup">
      <remove>&build_dir;/&gcc-directory;</remove>
      <remove>&build_dir;/gcc-build</remove>
    </stage>
  </package>
</alfs>

=== 01Hub/ALFS/profiles/BLFS/trunk/chapter16/libsoup.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd" [
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/packages/ch16.ent">
<!ENTITY % config_entities SYSTEM  "../config/config.ent">

%general_entities;
%package_entities;
%config_entities;

]>

<alfs>
<package name="libsoup" version="&libsoup-version;">

	<packageinfo>
		<requires><name>glib2</name></requires>
		<utilizes><name>gtk-doc</name></utilizes>
		<utilizes><name>openssl</name></utilizes>
		<utilizes><name>gnutls</name></utilizes>
	</packageinfo>

	<stage name="Unpacking">
		<unpack>
			<archive>&packages_dir;/&libsoup-package;</archive>
			<destination>&build_dir;</destination>
		</unpack>
	</stage>

	<stage name="Installing">
		<stageinfo>
			<base>&build_dir;/&libsoup-directory;</base>
		</stageinfo>

		<configure>
			<param>--prefix=/usr</param>
			<param>--libexecdir=/usr/sbin</param>
		</configure>

		<make />

		<make>
			<param>install</param>
		</make>
	</stage>

	<stage name="Cleanup">
		<remove>&build_dir;/&libsoup-directory;</remove>
	</stage>

</package>
</alfs>

=== 01Hub/ALFS/profiles/BLFS/trunk/chapter12/perlmods/Digest-BubbleBabble.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../../config/general.ent">
<!ENTITY % package_entities SYSTEM "../../config/packages/ch12.ent">
<!ENTITY % config_entities SYSTEM  "../../config/config.ent">

%general_entities;
%package_entities;
%config_entities;

]>
<alfs>
  <package name="Digest-BubbleBabble" version="&Digest-BubbleBabble-version;">
    <stage name="Unpacking">
      <unpack>
      	<digest>&Digest-BubbleBabble-md5;</digest>
        <archive>&packages_dir;/&Digest-BubbleBabble-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Installing">
      <stageinfo>
        <base>&build_dir;/&Digest-BubbleBabble-directory;</base>
      </stageinfo>
      <execute command="perl Makefile.PL" />
      <make />
      <make>
        <param>test</param>
      </make>
      <make>
        <param>install</param>
      </make>
    </stage>
    <stage name="Cleanup">
      <remove>&build_dir;/&Digest-BubbleBabble-directory;</remove>
    </stage>
  </package>
</alfs>

=== 01Hub/ALFS/archive/profiles/LFS/trunk/chapter06/procps.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">

%general_entities;
%package_entities;
]>
<alfs>
  <package name="procps" version="&procps-version;">
    <stage name="Download and Check">
      <download>
	<file>&procps-package;</file>
	<url>&procps-package-url;</url>
	<destination>&packages_dir;</destination>
	<digest>&procps-md5;</digest>
      </download>
    </stage>
    <stage name="Unpacking">
      <unpack>
        <archive>&packages_dir;/&procps-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Installing">
      <stageinfo>
        <base>&build_dir;/&procps-directory;</base>
      </stageinfo>
      <make>
        <param>&jlevel;</param>
      </make>
      <make>
        <param>install</param>
      </make>
    </stage>
    <stage name="Cleanup">
      <remove>&build_dir;/&procps-directory;</remove>
    </stage>
  </package>
</alfs>
