=== 01Hub/ALFS/archive/DTD/trunk/ALFS.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
       ALFS :    Document Type Definition
       Version : SVN
       Author:   V. Dzuba
       Updates:  Kevin P. Fleming
       Date:     July 3, 2004

       The current version of the DTD is available at:
             http://www.linuxfromscratch.org/alfs/downloads/stable

       The current version of its documentation is available at:
             http://www.linuxfromscratch.org/alfs/view/dtd

       This DTD is published under both BSD and GNU licenses.
-->

<!ENTITY lt     "&#38;#60;"> 
<!ENTITY gt     "&#62;"> 
<!ENTITY amp    "&#38;#38;"> 
<!ENTITY apos   "&#39;"> 
<!ENTITY quot   "&#34;"> 

<!ENTITY % ops "configure | copy | download | execute | if | link | make | mkdir | move | ownership | patch | permissions | remove | search_replace | stage | textdump | unpack">
<!ENTITY % tests "test | package-built | package-version | and | or | not">

<!ELEMENT alfs           ((%ops; | include | package | packagegroup)+)>
<!ATTLIST alfs
          base           CDATA #IMPLIED
          version        CDATA #FIXED "3.2"
	  xml:base	 CDATA #IMPLIED
	  xmlns:xi	 CDATA #IMPLIED>

<!ELEMENT and            ((%tests;)+)>

<!ELEMENT archive        (#PCDATA)>

<!ELEMENT base           (#PCDATA)>

<!ELEMENT configure      ((param | prefix)*)>
<!ATTLIST configure
          base           CDATA #IMPLIED
          command        CDATA #IMPLIED>

<!ELEMENT content        (#PCDATA)>

<!ELEMENT copy           (option*, source+, destination)>
<!ATTLIST copy
          base           CDATA #IMPLIED>

<!ELEMENT description    (para | list)*>

<!ELEMENT destination    (#PCDATA)>

<!ELEMENT digest         (#PCDATA)>
<!ATTLIST digest         
          type           CDATA     "md5">

<!ELEMENT download       (file, url*, digest?)>
<!ATTLIST download
          base           CDATA #IMPLIED>

<!ELEMENT else           (stageinfo?, (%ops;)*)>

<!ELEMENT execute        (((param | prefix)*) | content)>
<!ATTLIST execute
          base           CDATA #IMPLIED
          command        CDATA #IMPLIED>

<!ELEMENT environment    (variable+)>

<!ELEMENT file           (#PCDATA)>

<!ELEMENT find           (#PCDATA)>

<!ELEMENT if		 ((%tests;)+, then?, else?)>

<!ELEMENT item           (#PCDATA)>

<!ELEMENT include        EMPTY>
<!ATTLIST include
          href           CDATA #REQUIRED>

<!ELEMENT link           (option*, target+, name)>
<!ATTLIST link
          base           CDATA #IMPLIED
	  type           (hard | symbolic) "symbolic">

<!ELEMENT list           (item | list)+>
<!ATTLIST list
          type           (bullet | number) "bullet">

<!ELEMENT make           ((param | prefix)*)>
<!ATTLIST make
          base           CDATA #IMPLIED>

<!ELEMENT mkdir          (option?, permissions?, name+)>
<!ATTLIST mkdir
          base           CDATA #IMPLIED>
          
<!ELEMENT move           (option?, source+, destination)>
<!ATTLIST move
          base           CDATA #IMPLIED>

<!ELEMENT name           (#PCDATA)>

<!ELEMENT not            (%tests;)>

<!ELEMENT option         (#PCDATA)>

<!ELEMENT or             ((%tests;)+)>

<!ELEMENT ownership      (option?, name+)>
<!ATTLIST ownership
          base           CDATA #IMPLIED
          user           CDATA #IMPLIED
	  group          CDATA #IMPLIED>
          
<!ELEMENT package        (packageinfo?, stage+)>
<!ATTLIST package
          name           CDATA #REQUIRED
          version        CDATA #REQUIRED>

<!ELEMENT packageinfo    (description?, requires*, utilizes*)>

<!ELEMENT packagegroup   (package+)>

<!ELEMENT para           (#PCDATA)>

<!ELEMENT param          (#PCDATA)>

<!ELEMENT patch          (digest?, reference*, file, (param | prefix)*)>
<!ATTLIST patch
          base           CDATA #IMPLIED
          mode           (forward | reverse) "forward"
          path_strip     CDATA #IMPLIED>

<!ELEMENT permissions    (option?, name*)>
<!ATTLIST permissions
          base           CDATA #IMPLIED
          mode           CDATA #REQUIRED>

<!ELEMENT prefix         (#PCDATA)>

<!ELEMENT reference      (#PCDATA)>

<!ELEMENT remove         (file+)>
<!ATTLIST remove
          base           CDATA #IMPLIED>

<!ELEMENT replace        (#PCDATA)>

<!ELEMENT requires       (name, version*)>

<!ELEMENT root           (#PCDATA)>

<!ELEMENT search_replace (file, find, replace)>
<!ATTLIST search_replace
          base           CDATA #IMPLIED
          mode           (append | replace | prepend) "replace"
          global         (yes | no) "yes">

<!ELEMENT shell          (#PCDATA)>

<!ELEMENT stage          (stageinfo?, (%ops; | package | packagegroup)+)>
<!ATTLIST stage
          name           CDATA #IMPLIED>
          
<!ELEMENT source         (#PCDATA)>

<!ELEMENT stageinfo      (root?, user?, environment?, base?, shell?)>

<!ELEMENT target         (#PCDATA)>

<!ELEMENT test           (#PCDATA)>

<!ELEMENT textdump       (file, content)>
<!ATTLIST textdump
          base           CDATA #IMPLIED
	  mode           (append | overwrite) "overwrite">

<!ELEMENT then           (stageinfo?, (%ops;)*)>

<!ELEMENT unpack         (digest?, reference*, archive)>
<!ATTLIST unpack
          base           CDATA #IMPLIED>

<!ELEMENT url            (#PCDATA)>

<!ELEMENT user           (#PCDATA)>

<!ELEMENT utilizes       (name, version*)>

<!ELEMENT variable       (#PCDATA)>
<!ATTLIST variable
          name           CDATA #REQUIRED
	  mode           (append | prepend) #IMPLIED>

<!ELEMENT version        (#PCDATA)>
<!ATTLIST version
          condition      (eq | ne | gt | ge | lt | le) #REQUIRED>

=== 01Hub/ALFS/profiles/BLFS/branches/build-as-user/chapter18/inetutils.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/packages/ch18.ent">
<!ENTITY % config_entities SYSTEM  "../config/config.ent">

%general_entities;
%package_entities;
%config_entities;

]>
<alfs>
  <package name="inetutils" version="&inetutils-version;">
    <packageinfo>
      <utilizes>
        <name>linuxpam</name>
      </utilizes>
      <utilizes>
        <name>tcpwrappers</name>
      </utilizes>
      <utilizes>
	<name>krb4</name>
      </utilizes>
      <utilizes>
	<name>&krb-impl;</name>
      </utilizes>
    </packageinfo>
    <stage name="Unpacking">
      <stageinfo>
	<user>&build-user;</user>
      </stageinfo>
      <unpack>
        <digest>&inetutils-md5;</digest>
	<archive>&packages_dir;/&inetutils-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Patching">
      <stageinfo>
	<user>&build-user;</user>
	<base>&build_dir;/&inetutils-directory;</base>
      </stageinfo>
      <patch>
	<param>-N</param>
	<param>-p1</param>
	<param>-i &packages_dir;/&inetutils-kernel-header-patch;</param>
      </patch>
    </stage>
    <stage name="Building">
      <stageinfo>
	<user>&build-user;</user>
        <base>&build_dir;/&inetutils-directory;</base>
      </stageinfo>
      <configure>
        <param>--prefix=/usr</param>
	<param>--libexecdir=/usr/sbin</param>
	<param>--sysconfdir=/etc</param>
	<param>--localstatedir=/var</param>
	<param>--mandir=/usr/share/man</param>
        <param>--infodir=/usr/share/info</param>
	<param>--disable-logger</param>
	<param>--disable-syslogd</param>
      </configure>
      <make />
    </stage>
    <stage name="Installing">
      <stageinfo>
	<base>&build_dir;/&inetutils-directory;</base>
      </stageinfo>
      <make>
        <param>install</param>
      </make>
      <move>
        <source>/usr/bin/ping</source>
        <destination>/bin</destination>
      </move>
    </stage>
    <stage name="Cleanup">
      <remove>&build_dir;/&inetutils-directory;</remove>
    </stage>
  </package>
</alfs>

=== 01Hub/ALFS/archive/profiles/BLFS/trunk/chapter12/perlmods/Module-Build.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../../config/general.ent">
<!ENTITY % package_entities SYSTEM "../../config/packages/ch12.ent">
<!ENTITY % config_entities SYSTEM  "../../config/config.ent">

%general_entities;
%package_entities;
%config_entities;

]>
<alfs>
  <package name="Module-Build" version="&Module-Build-version;">
    <packageinfo>
      <requires>
	<name>ExtUtils-ParseXS</name>
      </requires>
      <requires>
	<name>Archive-Tar</name>
      </requires>
      <requires>
	<name>YAML</name>
      </requires>
      <utilizes>
	<name>Module-Signature</name>
      </utilizes>
    </packageinfo>
    <stage name="Unpacking">
      <unpack>
      	<digest>&Module-Build-md5;</digest>
        <archive>&packages_dir;/&Module-Build-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Installing">
      <stageinfo>
        <base>&build_dir;/&Module-Build-directory;</base>
      </stageinfo>
      <execute command="perl Build.PL" />
      <execute command="./Build test" />
      <execute command="./Build install" />
    </stage>
    <stage name="Cleanup">
      <remove>&build_dir;/&Module-Build-directory;</remove>
    </stage>
  </package>
</alfs>

=== 01Hub/ALFS/profiles/LFS/branches/cross-lfs/final-system/findutils.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">
<!ENTITY % config_entities SYSTEM "../config/config.ent">

%general_entities;
%package_entities;
%config_entities;
]>
<alfs>
  <package name="findutils" version="&findutils-version;">
    <stage name="Unpacking">
      <unpack>
        <digest>&findutils-md5;</digest>
        <archive>&packages_dir;/&findutils-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Installing">
      <stageinfo>
        <base>&build_dir;/&findutils-directory;</base>
      </stageinfo>
      <configure>
        <param>--prefix=/usr</param>
        <param>--libexecdir=/usr/lib/locate</param>
        <param>--localstatedir=/var/lib/locate</param>
      </configure>
      <make>
        <param>&jlevel;</param>
      </make>
      <!--
      <make>
        <param>check</param>
      </make>
      -->
      <make>
        <param>install</param>
      </make>
    </stage>
    <stage name="Cleanup">
      <remove>&build_dir;/&findutils-directory;</remove>
    </stage>
  </package>
</alfs>

=== 01Hub/ALFS/archive/profiles/LFS/tags/6.1.1/chapter06/sysvinit.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">

%general_entities;
%package_entities;
]>
<alfs>
  <package name="sysvinit" version="&sysvinit-version;">
    <stage name="Unpacking">
      <unpack>
        <digest>&sysvinit-md5;</digest>
        <archive>&packages_dir;/&sysvinit-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Installing">
      <stageinfo>
        <base>&build_dir;/&sysvinit-directory;</base>
      </stageinfo>
      <search_replace>
        <file>src/init.c</file>
        <find>Sending processes</find>
        <replace>Sending processes started by init</replace>
      </search_replace>
      <make>
        <param>&jlevel;</param>
        <param>-C src</param>
      </make>
      <make>
        <param>-C src</param>
        <param>install</param>
      </make>
      <copy>
        <source>&skeleton_dir;/etc/inittab</source>
        <destination>/etc</destination>
      </copy>
    </stage>
    <stage name="Cleanup">
      <remove>&build_dir;/&sysvinit-directory;</remove>
    </stage>
  </package>
</alfs>

=== 01Hub/ALFS/archive/profiles/BLFS/branches/build-as-user/chapter08/libglade.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/packages/ch08.ent">
<!ENTITY % config_entities SYSTEM  "../config/config.ent">

%general_entities;
%package_entities;
%config_entities;

]>
<alfs>
  <package name="libglade" version="&libglade-version;">
    <packageinfo>
      <requires>
        <name>libxml2</name>
      </requires>
      <requires>
        <name>gtk+2</name>
      </requires>
      <utilizes>
        <name>python</name>
      </utilizes>
      <utilizes>
        <name>gtk-doc</name>
      </utilizes>
    </packageinfo>
    <stage name="Unpacking">
      <stageinfo>
	<user>&build-user;</user>
      </stageinfo>
      <unpack>
        <digest>&libglade-md5;</digest>
	<archive>&packages_dir;/&libglade-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Building">
      <stageinfo>
	<user>&build-user;</user>
	<base>&build_dir;/&libglade-directory;</base>
      </stageinfo>
      <configure>
	<param>--prefix=/usr</param>
      </configure>
      <make />
    </stage>
    <stage name="Installing">
      <stageinfo>
	<base>&build_dir;/&libglade-directory;</base>
      </stageinfo>
      <make>
	<param>install</param>
      </make>
      &ldconfig;
    </stage>
    <stage name="Cleanup">
      <remove>&build_dir;/&libglade-directory;</remove>
    </stage>
  </package>
</alfs>

=== 01Hub/ALFS/profiles/BLFS/trunk/chapter39/xine-ui.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/packages/ch39.ent">
<!ENTITY % config_entities SYSTEM  "../config/config.ent">

%general_entities;
%package_entities;
%config_entities;

]>
<alfs>
  <package name="xine-ui" version="&xine-ui-version;">
    <packageinfo>
      <requires>
        <name>xine-lib</name>
      </requires>
      <utilizes>
        <name>curl</name>
      </utilizes>
      <utilizes>
        <name>aalib</name>
      </utilizes>
    </packageinfo>
    <stage name="Unpacking">
      <unpack>
        <archive>&packages_dir;/&xine-ui-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Installing">
      <stageinfo>
        <base>&build_dir;/&xine-ui-directory;</base>
      </stageinfo>
      <configure>
        <param>--prefix=/usr</param>
      </configure>
      <make />
      <make>
        <param>install</param>
      </make>
    </stage>
    <stage name="Cleanup">
      <remove>&build_dir;/&xine-ui-directory;</remove>
    </stage>
  </package>
</alfs>

=== 01Hub/ALFS/profiles/BLFS/trunk/chapter31/gnome-mag.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/packages/ch31.ent">
<!ENTITY % config_entities SYSTEM  "../config/config.ent">

%general_entities;
%package_entities;
%config_entities;

]>
<alfs>
  <package name="gnome-mag" version="&gnome-mag-version;">
    <packageinfo>
      <requires>
        <name>libgail-gnome</name>
      </requires>
      <utilizes>
	<name>Xdamage</name>
      </utilizes>
    </packageinfo>
    <stage name="Unpacking">
      <unpack>
        <archive>&packages_dir;/&gnome-mag-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Installing">
      <stageinfo>
        <base>&build_dir;/&gnome-mag-directory;</base>
      </stageinfo>
      <configure>
        <param>--prefix=`pkg-config --variable=prefix ORBit-2.0`</param>
      </configure>
      <make />
      <make>
        <param>install</param>
      </make>
    </stage>
    <stage name="Cleanup">
      <remove>&build_dir;/&gnome-mag-directory;</remove>
    </stage>
  </package>
</alfs>

=== 01Hub/ALFS/profiles/BLFS/trunk/chapter30/libbonoboui.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/packages/ch30.ent">
<!ENTITY % config_entities SYSTEM  "../config/config.ent">

%general_entities;
%package_entities;
%config_entities;

]>
<alfs>
  <package name="libbonoboui" version="&libbonoboui-version;">
    <packageinfo>
      <requires>
        <name>libgnome</name>
      </requires>
      <requires>
        <name>libgnomecanvas</name>
      </requires>
      <utilizes>
        <name>gtk-doc</name>
      </utilizes>
    </packageinfo>
    <stage name="Unpacking">
      <unpack>
        <archive>&packages_dir;/&libbonoboui-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Installing">
      <stageinfo>
	<base>&build_dir;/&libbonoboui-directory;</base>
      </stageinfo>
      <configure>
	<param>--prefix=`pkg-config --variable=prefix ORBit-2.0`</param>
      </configure>
      <make />
      <make>
	<param>install</param>
      </make>
      <search_replace>
	<file>&gnome-prefix;/lib/bonobo/servers/Bonobo_Sample_Controls.server</file>
	<find>/gnome/head/INSTALL</find>
	<replace>&gnome-prefix;</replace>
      </search_replace>
      &ldconfig;
    </stage>
    <stage name="Cleanup">
      <remove>&build_dir;/&libbonoboui-directory;</remove>
    </stage>
  </package>
</alfs>
