=== 01Hub/ALFS/archive/DTD/trunk/ALFS.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
       ALFS :    Document Type Definition
       Version : SVN
       Author:   V. Dzuba
       Updates:  Kevin P. Fleming
       Date:     July 3, 2004

       The current version of the DTD is available at:
             http://www.linuxfromscratch.org/alfs/downloads/stable

       The current version of its documentation is available at:
             http://www.linuxfromscratch.org/alfs/view/dtd

       This DTD is published under both BSD and GNU licenses.
-->

<!ENTITY lt     "&#38;#60;"> 
<!ENTITY gt     "&#62;"> 
<!ENTITY amp    "&#38;#38;"> 
<!ENTITY apos   "&#39;"> 
<!ENTITY quot   "&#34;"> 

<!ENTITY % ops "configure | copy | download | execute | if | link | make | mkdir | move | ownership | patch | permissions | remove | search_replace | stage | textdump | unpack">
<!ENTITY % tests "test | package-built | package-version | and | or | not">

<!ELEMENT alfs           ((%ops; | include | package | packagegroup)+)>
<!ATTLIST alfs
          base           CDATA #IMPLIED
          version        CDATA #FIXED "3.2"
	  xml:base	 CDATA #IMPLIED
	  xmlns:xi	 CDATA #IMPLIED>

<!ELEMENT and            ((%tests;)+)>

<!ELEMENT archive        (#PCDATA)>

<!ELEMENT base           (#PCDATA)>

<!ELEMENT configure      ((param | prefix)*)>
<!ATTLIST configure
          base           CDATA #IMPLIED
          command        CDATA #IMPLIED>

<!ELEMENT content        (#PCDATA)>

<!ELEMENT copy           (option*, source+, destination)>
<!ATTLIST copy
          base           CDATA #IMPLIED>

<!ELEMENT description    (para | list)*>

<!ELEMENT destination    (#PCDATA)>

<!ELEMENT digest         (#PCDATA)>
<!ATTLIST digest         
          type           CDATA     "md5">

<!ELEMENT download       (file, url*, digest?)>
<!ATTLIST download
          base           CDATA #IMPLIED>

<!ELEMENT else           (stageinfo?, (%ops;)*)>

<!ELEMENT execute        (((param | prefix)*) | content)>
<!ATTLIST execute
          base           CDATA #IMPLIED
          command        CDATA #IMPLIED>

<!ELEMENT environment    (variable+)>

<!ELEMENT file           (#PCDATA)>

<!ELEMENT find           (#PCDATA)>

<!ELEMENT if		 ((%tests;)+, then?, else?)>

<!ELEMENT item           (#PCDATA)>

<!ELEMENT include        EMPTY>
<!ATTLIST include
          href           CDATA #REQUIRED>

<!ELEMENT link           (option*, target+, name)>
<!ATTLIST link
          base           CDATA #IMPLIED
	  type           (hard | symbolic) "symbolic">

<!ELEMENT list           (item | list)+>
<!ATTLIST list
          type           (bullet | number) "bullet">

<!ELEMENT make           ((param | prefix)*)>
<!ATTLIST make
          base           CDATA #IMPLIED>

<!ELEMENT mkdir          (option?, permissions?, name+)>
<!ATTLIST mkdir
          base           CDATA #IMPLIED>
          
<!ELEMENT move           (option?, source+, destination)>
<!ATTLIST move
          base           CDATA #IMPLIED>

<!ELEMENT name           (#PCDATA)>

<!ELEMENT not            (%tests;)>

<!ELEMENT option         (#PCDATA)>

<!ELEMENT or             ((%tests;)+)>

<!ELEMENT ownership      (option?, name+)>
<!ATTLIST ownership
          base           CDATA #IMPLIED
          user           CDATA #IMPLIED
	  group          CDATA #IMPLIED>
          
<!ELEMENT package        (packageinfo?, stage+)>
<!ATTLIST package
          name           CDATA #REQUIRED
          version        CDATA #REQUIRED>

<!ELEMENT packageinfo    (description?, requires*, utilizes*)>

<!ELEMENT packagegroup   (package+)>

<!ELEMENT para           (#PCDATA)>

<!ELEMENT param          (#PCDATA)>

<!ELEMENT patch          (digest?, reference*, file, (param | prefix)*)>
<!ATTLIST patch
          base           CDATA #IMPLIED
          mode           (forward | reverse) "forward"
          path_strip     CDATA #IMPLIED>

<!ELEMENT permissions    (option?, name*)>
<!ATTLIST permissions
          base           CDATA #IMPLIED
          mode           CDATA #REQUIRED>

<!ELEMENT prefix         (#PCDATA)>

<!ELEMENT reference      (#PCDATA)>

<!ELEMENT remove         (file+)>
<!ATTLIST remove
          base           CDATA #IMPLIED>

<!ELEMENT replace        (#PCDATA)>

<!ELEMENT requires       (name, version*)>

<!ELEMENT root           (#PCDATA)>

<!ELEMENT search_replace (file, find, replace)>
<!ATTLIST search_replace
          base           CDATA #IMPLIED
          mode           (append | replace | prepend) "replace"
          global         (yes | no) "yes">

<!ELEMENT shell          (#PCDATA)>

<!ELEMENT stage          (stageinfo?, (%ops; | package | packagegroup)+)>
<!ATTLIST stage
          name           CDATA #IMPLIED>
          
<!ELEMENT source         (#PCDATA)>

<!ELEMENT stageinfo      (root?, user?, environment?, base?, shell?)>

<!ELEMENT target         (#PCDATA)>

<!ELEMENT test           (#PCDATA)>

<!ELEMENT textdump       (file, content)>
<!ATTLIST textdump
          base           CDATA #IMPLIED
	  mode           (append | overwrite) "overwrite">

<!ELEMENT then           (stageinfo?, (%ops;)*)>

<!ELEMENT unpack         (digest?, reference*, archive)>
<!ATTLIST unpack
          base           CDATA #IMPLIED>

<!ELEMENT url            (#PCDATA)>

<!ELEMENT user           (#PCDATA)>

<!ELEMENT utilizes       (name, version*)>

<!ELEMENT variable       (#PCDATA)>
<!ATTLIST variable
          name           CDATA #REQUIRED
	  mode           (append | prepend) #IMPLIED>

<!ELEMENT version        (#PCDATA)>
<!ATTLIST version
          condition      (eq | ne | gt | ge | lt | le) #REQUIRED>

=== 01Hub/ALFS/archive/profiles/LFS/branches/testing-CD/chapter06/glibc.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd" [
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">

%general_entities;
%package_entities;
]>

<alfs>

<package name="glibc" version="&glibc-version;">
	<stage name="Unpacking.">
		<unpack>
			<archive>&packages_dir;/&glibc-package;</archive>
			<destination>&build_dir;</destination>
		</unpack>

		<mkdir base="&build_dir;">
			<option>parents</option>
			<name>glibc-build</name>
		</mkdir>
	</stage>

	<stage name="Installing.">
		<stageinfo>
			<environment>
				<variable name="CFLAGS" />
				<variable name="CXXFLAGS" />
			</environment>
			<base>&build_dir;/glibc-build</base>
		</stageinfo>

		<configure command="../&glibc-directory;/configure">
			<param>--prefix=/usr</param>
			<param>--disable-profile</param>
			<param>--enable-add-ons=nptl</param>
			<param>--with-tls</param>
			<param>--with-__thread</param>
			<param>--enable-kernel=2.6.0</param>
			<param>--without-cvs</param>
			<param>--libexecdir=/usr/lib/glibc</param>
			<param>--with-headers=/tools/glibc-kernheaders</param>
		</configure>

		<make />

		<make>
			<param>check</param>
		</make>

		<execute command="touch">
			<param>/etc/ld.so.conf</param>
		</execute>

		<make>
			<param>install</param>
		</make>

		<mkdir>
			<option>parents</option>
			<name>/usr/lib/locale</name>
		</mkdir>

		<execute command="localedef -i de_DE -f ISO-8859-1 de_DE" />
		<execute command="localedef -i de_DE@euro -f ISO-8859-15 de_DE@euro" />
		<execute command="localedef -i en_HK -f ISO-8859-1 en_HK" />
		<execute command="localedef -i en_PH -f ISO-8859-1 en_PH" />
		<execute command="localedef -i en_US -f ISO-8859-1 en_US" />
		<execute command="localedef -i es_MX -f ISO-8859-1 es_MX" />
		<execute command="localedef -i fa_IR -f UTF-8 fa_IR" />
		<execute command="localedef -i fr_FR -f ISO-8859-1 fr_FR" />
		<execute command="localedef -i fr_FR@euro -f ISO-8859-15 fr_FR@euro" />
		<execute command="localedef -i it_IT -f ISO-8859-1 it_IT" />
		<execute command="localedef -i ja_JP -f EUC-JP ja_JP" />

		<make>
			<param>-C ../&glibc-directory;/linuxthreads/man</param>
		</make>

		<make>
			<param>-C ../&glibc-directory;/linuxthreads/man</param>
			<param>install</param>
		</make>
	</stage>

	<stage name="Configuring.">
		<textdump>
			<file>/etc/nsswitch.conf</file>
			<content>
				=# Begin /etc/nsswitch.conf
				=
				=passwd: files
				=group: files
				=shadow: files
				=
				=hosts: files dns
				=networks: files
				=
				=protocols: files
				=services: files
				=ethers: files
				=rpc: files
				=
				=# End /etc/nsswitch.conf
			</content>
		</textdump>

		<remove>/etc/localtime</remove>
		<copy>
			<option>force</option>
			<source>&localtime;</source>
			<destination>/etc/localtime</destination>
		</copy>

		<textdump>
			<file>/etc/ld.so.conf</file>
			<content>
				=# Begin /etc/ld.so.conf
				=
				=/usr/local/lib
				=/opt/lib
				=
				=# End /etc/ld.so.conf
			</content>
		</textdump>
	</stage>

	<stage name="Cleaning up.">
		<remove>&build_dir;/&glibc-directory;</remove>
		<remove>&build_dir;/glibc-build</remove>
	</stage>
</package>

</alfs>

=== 01Hub/ALFS/archive/profiles/LFS/trunk/chapter06/ncurses.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">

%general_entities;
%package_entities;
]>
<alfs>
  <package name="ncurses" version="&ncurses-version;">
    <stage name="Download and Check">
      <download>
	<file>&ncurses-package;</file>
	<url>&ncurses-package-url;</url>
	<destination>&packages_dir;</destination>
	<digest>&ncurses-md5;</digest>
      </download>
    </stage>
    <stage name="Unpacking">
      <unpack>
        <archive>&packages_dir;/&ncurses-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Installing">
      <stageinfo>
        <base>&build_dir;/&ncurses-directory;</base>
      </stageinfo>
      <configure>
        <param>--prefix=/usr</param>
        <param>--with-shared</param>
        <param>--without-debug</param>
      </configure>
      <make>
        <param>sources</param>
      </make>
      <make>
        <param>&jlevel;</param>
      </make>
      <make>
        <param>install</param>
      </make>
      <permissions mode="755">
        <name>/usr/lib/*.&ncurses-version;</name>
      </permissions>
      <permissions mode="644">
        <name>/usr/lib/libncurses++.a</name>
      </permissions>
      <move>
        <source>/usr/lib/libncurses.so.5*</source>
        <destination>/lib</destination>
      </move>
      <link>
        <option>force</option>
        <target>../../lib/libncurses.so.5</target>
        <name>/usr/lib/libncurses.so</name>
      </link>
      <link>
        <option>force</option>
        <target>libncurses.so</target>
        <name>/usr/lib/libcurses.so</name>
      </link>
    </stage>
    <stage name="Cleanup">
      <remove>&build_dir;/&ncurses-directory;</remove>
    </stage>
  </package>
</alfs>

=== 01Hub/ALFS/profiles/LFS/branches/syntax-3.2/chapter06/udev.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd" [
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/package.ent">

%general_entities;
%package_entities;
]>

<alfs>

<package name="udev" version="&udev-version;">
	<stage name="Unpacking">
		<unpack base="&build_dir;">
			<digest>&udev-md5;</digest>
			<archive>&packages_dir;/&udev-package;</archive>
		</unpack>
	</stage>

	<stage name="Installing">
		<stageinfo>
			<base>&build_dir;/&udev-directory;</base>
		</stageinfo>

		<make>
		  	<param>udevdir=/dev</param>
		</make>

		<make>
		  	<param>udevdir=/dev</param>
			<param>install</param>
		</make>

		<copy base="&packages_dir;">
        		<option>force</option>
        		<source>&udev-permissions-file;</source>
        		<destination>/etc/udev/permissions.d/00-lfs.permissions</destination>
		</copy>

		<copy base="&packages_dir;">
        		<option>force</option>
        		<source>&udev-rules-file;</source>
        		<destination>/etc/udev/rules.d/00-lfs.rules</destination>
		</copy>		
	</stage>

	<stage name="Cleanup">
		<remove>
			<file>&build_dir;/&udev-directory;</file>
		</remove>
	</stage>
</package>

</alfs>

=== 01Hub/ALFS/archive/profiles/BLFS/trunk/chapter35/mozilla.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/packages/ch35.ent">
<!ENTITY % config_entities SYSTEM  "../config/config.ent">

%general_entities;
%package_entities;
%config_entities;

]>
<alfs>
  <package name="mozilla" version="&mozilla-version;">
    <packageinfo>
      <requires>
        <name>zip</name>
      </requires>
      <requires>
        <name>gtk+2</name>
      </requires>
      <requires>
        <name>libidl</name>
      </requires>
      <utilizes>
	<name>gnupg</name>
      </utilizes>
      <utilizes>
	<name>libjpeg</name>
      </utilizes>
      <utilizes>
	<name>unzip</name>
      </utilizes>
      <utilizes>
	<name>gnome-vfs2</name>
      </utilizes>
      <utilizes>
	<name>libart_lgpl</name>
      </utilizes>
      <utilizes>
	<name>&krb-impl;</name>
      </utilizes>
      <utilizes>
	<name>doxygen</name>
      </utilizes>
      <utilizes>
	<name>xprint</name>
      </utilizes>
      <utilizes>
	<name>electricfence</name>
      </utilizes>
      <utilizes>
	<name>cairo</name>
      </utilizes>
    </packageinfo>
    <stage name="Unpacking">
      <unpack>
        <digest>&mozilla-md5;</digest>
	<archive>&packages_dir;/&mozilla-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Installing">
      <stageinfo>
        <environment>
          <variable name="MOZILLA_OFFICIAL">1</variable>
          <variable name="BUILD_OFFICIAL">1</variable>
	  <variable name="MOZ_CO_PROJECT">suite</variable>
        </environment>
        <base>&build_dir;/&mozilla-directory;</base>
      </stageinfo>
      <configure>
        <param>--prefix=/usr</param>
        <param>--with-default-mozilla-five-home=/usr/lib/mozilla</param>
        <param>--with-system-zlib</param>
        <param>--with-system-png</param>
	<param>--enable-application=suite</param>
        <param>--enable-default-toolkit=gtk2</param>
	<param>--enable-extensions=all</param>
	<param>--enable-crypto</param>
	<param>--enable-xft</param>
	<param>--enable-xinerama</param>
	<param>--enable-optimize</param>
	<param>--enable-reorder</param>
	<param>--enable-strip</param>
	<param>--enable-cpp-rtti</param>
	<param>--enable-calendar</param>
	<param>--disable-freetype2</param>
	<param>--disable-accessibility</param>
	<param>--disable-debug</param>
	<param>--disable-tests</param>
	<param>--disable-logging</param>
	<param>--disable-pedantic</param>
	<param>--disable-installer</param>
      </configure>
      <make />
      <make>
        <param>install</param>
      </make>
      <mkdir>
	<option>parents</option>
	<name>/usr/include/mozilla-&mozilla-version;/nss</name>
      </mkdir>
      <execute command="cp -Lf dist/private/nss/*.h dist/public/nss/*.h /usr/include/mozilla-&mozilla-version;/nss" />
      <execute command="ln -nsf mozilla-&mozilla-version; /usr/include/mozilla" />
      <execute command="if [ -d /usr/lib/mozilla/plugins ]; then mv /usr/lib/mozilla/plugins/* /usr/lib/mozilla-&mozilla-version;/plugins; rm -rf /usr/lib/mozilla; fi" />
      <execute command="ln -nsf mozilla-&mozilla-version; /usr/lib/mozilla" />
      <move base="/usr/lib/mozilla-&mozilla-version;">
        <source>libnspr4.so</source>
        <source>libplc4.so</source>
        <source>libplds4.so</source>
        <source>libnss3.so</source>
        <source>libsmime3.so</source>
        <source>libsoftokn3.so</source>
        <source>libssl3.so</source>
        <source>libsoftokn3.chk</source>
        <destination>/usr/lib</destination>
      </move>
      <link>
        <option>force</option>
        <target>../libnspr4.so</target>
        <target>../libplc4.so</target>
        <target>../libplds4.so</target>
        <target>../libnss3.so</target>
        <target>../libsmime3.so</target>
        <target>../libsoftokn3.so</target>
        <target>../libssl3.so</target>
        <target>../libsoftokn3.chk</target>
        <name>/usr/lib/mozilla-&mozilla-version;</name>
      </link>
      <stage name="Multi-User Operation Setup">
        <stageinfo>
          <environment>
            <variable name="LD_LIBRARY_PATH">/usr/lib/mozilla-&mozilla-version;</variable>
            <variable name="MOZILLA_FIVE_HOME">/usr/lib/mozilla-&mozilla-version;</variable>
          </environment>
          <base>/usr/lib/mozilla-&mozilla-version;</base>
        </stageinfo>
        <execute command="./regxpcom" />
        <execute command="./regchrome" />
        <execute command="touch `find . -name *.rdf`" />
      </stage>
    </stage>
    <stage name="Cleanup">
      <remove>&build_dir;/&mozilla-directory;</remove>
    </stage>
  </package>
</alfs>

=== 01Hub/ALFS/profiles/BLFS/trunk/chapter27/xfce/xfdesktop.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../../config/general.ent">
<!ENTITY % package_entities SYSTEM "../../config/packages/ch27.ent">
<!ENTITY % config_entities SYSTEM  "../../config/config.ent">

%general_entities;
%package_entities;
%config_entities;

]>
<alfs>
<package name="xfdesktop" version="&xfce-xfdesktop-version;">
  <stage name="Unpacking.">
    <unpack>
      <digest>&xfce-xfdesktop-md5;</digest>
      <archive>&build_dir;/&xfce-build-directory;/&xfce-xfdesktop-package;</archive>
      <destination>&build_dir;/&xfce-build-directory;</destination>
    </unpack>
  </stage>
  <stage name="Installing.">
    <stageinfo>
      <base>&build_dir;/&xfce-build-directory;/&xfce-xfdesktop-directory;</base>
    </stageinfo>
    <configure>
      <param>--prefix=/usr</param>
      <param>--sysconfdir=/etc</param>
    </configure>
    <make />
    <make>
      <param>install</param>
    </make>
  </stage>
  <stage name="Cleanup.">
    <remove>&build_dir;/&xfce-build-directory;/&xfce-xfdesktop-directory;</remove>
  </stage>
</package>
</alfs>

=== 01Hub/ALFS/archive/profiles/BLFS/trunk/chapter20/procmail.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/packages/ch20.ent">
<!ENTITY % config_entities SYSTEM  "../config/config.ent">

%general_entities;
%package_entities;
%config_entities;

]>
<alfs>
  <package name="procmail" version="&procmail-version;">
    <stage name="Unpacking">
      <unpack>
        <digest>&procmail-md5;</digest>
	<archive>&packages_dir;/&procmail-package;</archive>
        <destination>&build_dir;</destination>
      </unpack>
    </stage>
    <stage name="Installing">
      <stageinfo>
        <base>&build_dir;/&procmail-directory;</base>
      </stageinfo>
      <make>
        <param>LOCKINGTEST=/tmp</param>
        <param>install</param>
      </make>
      <make>
        <param>install-suid</param>
      </make>
    </stage>
    <stage name="Cleanup">
      <remove>&build_dir;/&procmail-directory;</remove>
    </stage>
  </package>
</alfs>

=== 01Hub/ALFS/profiles/BLFS/trunk/chapter30/librsvg.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd" [
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/packages/ch30.ent">
<!ENTITY % config_entities SYSTEM  "../config/config.ent">

%general_entities;
%package_entities;
%config_entities;

]>

<alfs>
<package name="librsvg" version="&librsvg-version;">

        <packageinfo>
                <requires><name>gtk+2</name></requires>
                <requires><name>libxml2</name></requires>
                <requires><name>libart-lgpl</name></requires>
		<requires><name>popt</name></requires>
		<utilizes><name>libgsf</name></utilizes>
		<utilizes><name>libcroco</name></utilizes>
		<utilizes><name>gtk-doc</name></utilizes>
        </packageinfo>

	<stage name="Unpacking">
		<unpack>
			<archive>&packages_dir;/&librsvg-package;</archive>
			<destination>&build_dir;</destination>
		</unpack>
	</stage>

	<stage name="Installing">
		<stageinfo>
			<base>&build_dir;/&librsvg-directory;</base>
		</stageinfo>

		<configure>
			<param>--prefix=`pkg-config --variable=prefix ORBit-2.0`</param>
			<param>--sysconfdir=/etc/gnome</param>
			<param>--disable-gtk-doc</param>
		</configure>

		<make/>

		<make>
			<param>install</param>
		</make>

		&ldconfig;
	</stage>

	<stage name="Cleanup">
		<remove>&build_dir;/&librsvg-directory;</remove>
	</stage>

</package>
</alfs>

=== 01Hub/ALFS/archive/profiles/BLFS/trunk/chapter12/perlmodules.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE alfs SYSTEM "../DTD/ALFS.dtd"
[
<!ENTITY % general_entities SYSTEM "../config/general.ent">
<!ENTITY % package_entities SYSTEM "../config/packages/ch12.ent">
<!ENTITY % config_entities SYSTEM  "../config/config.ent">

%general_entities;
%package_entities;
%config_entities;

]>
<alfs xmlns:xi="http://www.w3.org/2001/XInclude">
  <stage name="Perl modules">
    <!-- Note: Some modules are built in a specific order to satisfy dependencies -->
    <xi:include href="perlmods/Module-Info.xml" />
    
    <xi:include href="perlmods/Pod-Escapes.xml" />
    <xi:include href="perlmods/Pod-Simple.xml" />
    <xi:include href="perlmods/Test-Builder-Tester.xml" />
    <xi:include href="perlmods/Test-Pod.xml" />

    <xi:include href="perlmods/Extutils-CBuilder.xml" />
    <xi:include href="perlmods/Extutils-ParseXS.xml" />
    <xi:include href="perlmods/Compress-Zlib.xml" />
    <xi:include href="perlmods/IO-Zlib.xml" />
    <xi:include href="perlmods/Archive-Tar.xml" />
    <xi:include href="perlmods/YAML.xml" />
    <xi:include href="perlmods/Module-Build.xml" />

    <xi:include href="perlmods/HTML-Tagset.xml" />
    <xi:include href="perlmods/HTML-Parser.xml" />

    <xi:include href="perlmods/XML-Parser.xml" />

    <xi:include href="perlmods/SGMLSpm.xml" />

    <xi:include href="perlmods/Tk.xml" />

    <xi:include href="perlmods/Digest-SHA1.xml" />
    <xi:include href="perlmods/Digest-HMAC.xml" />
    <xi:include href="perlmods/Net-IP.xml" />
    <xi:include href="perlmods/Net-DNS.xml" />

    <xi:include href="perlmods/Module-CoreList.xml" />
    <xi:include href="perlmods/Test-Prereq.xml" />
    <xi:include href="perlmods/Business-ISBN-Data.xml" />
    <xi:include href="perlmods/Business-ISBN.xml" />
    <xi:include href="perlmods/URI.xml" />
    <xi:include href="perlmods/Crypt-SSLeay.xml" />
    <xi:include href="perlmods/LWP.xml" />

    <xi:include href="perlmods/DateManip.xml" />

    <xi:include href="perlmods/HTML-TableExtract.xml" />
    <xi:include href="perlmods/Finance-Quote.xml" />

    <xi:include href="perlmods/Text-CSV_XS.xml" />
    <xi:include href="perlmods/Finance-QuoteHist.xml" />

    <xi:include href="perlmods/Digest-SHA.xml" />
    <xi:include href="perlmods/PAR-Dist.xml" />
    <xi:include href="perlmods/Module-Signature.xml" />
        
    <xi:include href="perlmods/Digest-BubbleBabble.xml" />

    <xi:include href="perlmods/Socket6.xml" />
    <xi:include href="perlmods/IO-Socket-INET6.xml" />
    

  </stage>
</alfs>
